#!/bin/bash
# Migration: Create 'up' group and set up theme permissions for existing systems
# This migration brings existing installations up to date with the new user management system

set -euo pipefail

echo "=== Migration 001: User Group and Theme Permissions ==="

# Get UP_ROOT
UP_ROOT="${UP_ROOT:-/usr/local/share/up}"

# 1. Create 'up' group if it doesn't exist
if ! getent group up &>/dev/null; then
    echo "→ Creating 'up' group..."
    groupadd up
    echo "✓ Created 'up' group"
else
    echo "✓ 'up' group already exists"
fi

# 2. Add existing users to the 'up' group
echo "→ Adding existing users to 'up' group..."
for user_home in /home/*; do
    if [ -d "$user_home" ] && [ -f "$user_home/.bashrc" ]; then
        username=$(basename "$user_home")
        # Check if user is already in the 'up' group
        if groups "$username" | grep -q "\bup\b"; then
            echo "   ✓ $username already in 'up' group"
        else
            usermod -aG up "$username"
            echo "   ✓ Added $username to 'up' group"
        fi
    fi
done

# 3. Create lightdm-gtk-greeter.conf.d directory
echo "→ Creating LightDM greeter config directory..."
mkdir -p /etc/lightdm/lightdm-gtk-greeter.conf.d
echo "✓ Created /etc/lightdm/lightdm-gtk-greeter.conf.d"

# 4. Create theme.conf with proper permissions
THEME_CONF="/etc/lightdm/lightdm-gtk-greeter.conf.d/theme.conf"
if [ ! -f "$THEME_CONF" ]; then
    echo "→ Creating theme.conf..."
    cat > "$THEME_CONF" << 'EOF'
# LightDM GTK Greeter Theme Configuration
# Auto-generated by migration script - users in 'up' group can modify without sudo
# This file overrides values from /etc/lightdm/lightdm-gtk-greeter.conf

[greeter]
# Theme will be set by up-switch-theme
theme-name = Materia
background = /usr/share/backgrounds/archlinux/geowaves.png
EOF
    chown root:up "$THEME_CONF"
    chmod 664 "$THEME_CONF"
    echo "✓ Created theme.conf with root:up ownership"
else
    echo "✓ theme.conf already exists"
    # Update permissions if needed
    chown root:up "$THEME_CONF" 2>/dev/null || true
    chmod 664 "$THEME_CONF" 2>/dev/null || true
    echo "✓ Updated theme.conf permissions"
fi

# 5. Copy up-add-user script to /usr/local/bin/
if [ -f "$UP_ROOT/bin/up-add-user" ]; then
    echo "→ Installing up-add-user script..."
    cp "$UP_ROOT/bin/up-add-user" /usr/local/bin/up-add-user
    chmod +x /usr/local/bin/up-add-user
    echo "✓ Installed up-add-user to /usr/local/bin/"
else
    echo "⚠ up-add-user script not found in $UP_ROOT/bin/"
fi

# 6. Copy updated desktop background scripts
if [ -f "$UP_ROOT/bin/up-select-desktop-image" ]; then
    echo "→ Updating up-select-desktop-image..."
    cp "$UP_ROOT/bin/up-select-desktop-image" /usr/local/bin/up-select-desktop-image
    chmod +x /usr/local/bin/up-select-desktop-image
    echo "✓ Updated up-select-desktop-image"
fi

if [ -f "$UP_ROOT/bin/up-random-desktop-image" ]; then
    echo "→ Updating up-random-desktop-image..."
    cp "$UP_ROOT/bin/up-random-desktop-image" /usr/local/bin/up-random-desktop-image
    chmod +x /usr/local/bin/up-random-desktop-image
    echo "✓ Updated up-random-desktop-image"
fi

# 7. Copy updated system menu script
if [ -f "$UP_ROOT/configs/scripts/system-menu.sh" ]; then
    echo "→ Updating system menu..."
    for user_home in /home/*; do
        if [ -d "$user_home" ] && [ -f "$user_home/.bashrc" ]; then
            username=$(basename "$user_home")
            user_config_dir="$user_home/.config/scripts"
            mkdir -p "$user_config_dir"
            cp "$UP_ROOT/configs/scripts/system-menu.sh" "$user_config_dir/system-menu.sh"
            chmod +x "$user_config_dir/system-menu.sh"
            chown -R "$username:$username" "$user_config_dir"
            echo "✓ Updated system menu for $username"
        fi
    done
fi

# 8. Note: switch-theme.sh is already in the correct location
# No need to copy it as it would be copying to itself

echo ""
echo "=== Migration 001 Complete ==="
echo "The following changes were made:"
echo "  - Created 'up' group for system users"
echo "  - Added existing users to 'up' group"
echo "  - Created LightDM greeter config directory"
echo "  - Created theme.conf with group-writable permissions"
echo "  - Installed up-add-user script"
echo "  - Updated desktop background scripts"
echo "  - Updated system menu with Add User option"
echo ""
echo "Users in the 'up' group can now:"
echo "  - Change themes without sudo"
echo "  - Change desktop backgrounds (updates LightDM greeter)"
echo "  - Add new users via the system menu"
echo ""