# XLibre i3 Zsh config — clean + Starship + dev tools

# History
HISTSIZE=10000
SAVEHIST=10000
setopt SHARE_HISTORY APPEND_HISTORY

# Completion (reuse dump unless it is a week old — skips the slow security scan)
autoload -Uz compinit
if [[ -f ${ZDOTDIR:-$HOME}/.zcompdump && -z $(find ${ZDOTDIR:-$HOME}/.zcompdump -mtime +7 2>/dev/null) ]]; then
  compinit -C -u
else
  compinit -u
fi

# Aliases (developer friendly)
alias ls='eza --icons'
alias ll='eza -lah --icons'
alias cat='bat'
alias vim='nvim'
alias update='sudo /usr/local/share/up/update.sh'
# zoxide provides 'z' for quick directory jumping - use 'z <dir>' or 'z -l' to list
eval "$(zoxide init zsh)"

# Starship prompt
eval "$(starship init zsh)"

# Theme colors (auto-generated by switch-theme.sh - do not edit)
[[ -f ~/.config/zsh/theme.zsh ]] && source ~/.config/zsh/theme.zsh
